application:
  subdomain: backrest
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://backrest:9898/
services:
  backrest:
    # upstream: docker.io/garethgeorge/backrest:v1.14.1
    image: registry.lazycat.cloud/czyt/garethgeorge/backrest:79236b51936456c5
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/config:/config
      - /lzcapp/cache/backrest:/cache
      - /lzcapp/var/userdata:/userdata
      - /lzcapp/var/rclone:/root/.config/rclone
      - /lzcapp/var/repos:/repos
